---
title: "Reading and writing sound files"
author: "Bob Horton...sure...yeah...totoally..k, it is"
date: "July 14, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("knitr")
opts_knit$set(root.dir = "~/eulers disk/")
```

## Sound I/O

```{r seewave_example}
library("seewave")

# 100 millisecond sample of a 440 Hz sine wave
s1 <- sin(2*pi*440*seq(0,1/10,length.out=800))
oscillo(s1, f=8000)
#is this example really necessary?
```


### Read WAV file

For demonstration purposes, we use this [WAV file](http://www.nch.com.au/acm/8k8bitpcm.wav) from the Wikipedia artcle on the [WAV](https://en.wikipedia.org/wiki/WAV) format. Only uncompressed PCM and IEEE_FLOAT Wave formats supported.

```{r read_wav}
library("tuneR")
wf_number <- "1"
wave_file <- paste0("eulersDiskTestComMic", wf_number, ".wav")
s6 <- readWave(wave_file)

s6

s7 <- readWave(wave_file, from = 1, to = 5, units = "seconds")
s7
s7@samp.rate
s7@bit
s7@stereo

```
### Plot WAV

```{r plot_wav}
str(s7)

hist(s7@left, breaks=30, xlab="Amplitude")

plot(s7@left, type='l')
abline(v=s7@samp.rate * (0:5), col="red")

recording_length <- function(wave_obj){
  length(wave_obj@left)/wave_obj@samp.rate
}

recording_length(s6)
#this just says how to get the recording length?


#save wave file
#wave_f <- WaveMC(as.vector(f), samp.rate=8000, bit =  16)
#writeWave(wave_f, file="SmoothedeulersDiskTestComMic1.wav")


```
Read in wave file, one second slice at a time, smooth and save file. 
```{r}
# Filter of length 20 points
g <- gausswin(175)
SLICES_DIR <- "slices 2"
dir.create(SLICES_DIR, showWarnings = FALSE)
#showwarnings=false?
whole_seconds <- floor(recording_length(s6))
#this is taking the "floor" of the recording?
for (i in 1:whole_seconds){
  wav_file_name <- file.path(SLICES_DIR, sprintf("fslice_%02d.wav", i))
  sound_slice <- readWave(wave_file, 
                          from = whole_seconds - i, 
                          to = whole_seconds - i + 1, 
                          units = "seconds")
  
  ### SMOOTHER

  # Filtered signal
  z <- sound_slice@left
  f <- stats::filter(z, g,  circular=T) 
  
  w <- normalize(Wave(left = as.numeric(round(f)),samp.rate=8000, bit =16), unit="16")
  writeWave(sound_slice, paste0(AUDIO_PATH, "\\slices 2\\wsmooth_", slice_no, ".wav"))
}
#this is tellin how to chop up the files?
list.files(path=SLICES_DIR, pattern="*.wav")
#this tells to put the slices in the wav?
```


## References

* https://cran.r-project.org/web/packages/seewave/vignettes/seewave_IO.pdf

